apiVersion: velero.io/v1
kind: Backup
metadata:
  name: test-backup
  namespace: velero-ns
  annotations:
    velero.io/csi-volumesnapshot-class_disk.csi.cloud.com: "csi-vsphere-vsc"
spec:
  includedNamespaces:
  - velero-ns
