apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    component: velero
  name: default
  namespace: velero-ns
spec:
  config:
    region: <___>   !!!
    s3ForcePathStyle: "true"
    s3Url: <___>  !!!
  objectStorage:
    bucket: <___>  !!!
  provider: aws
