apiVersion: velero.io/v1
kind: Restore
metadata:
  name: test-restore-schedule
  namespace: velero-ns
spec:
  backupName: <___>   !!!
  includedNamespaces:
  - 'velero-ns'
  includedResources:
  - 'pv'
  - 'pvc'
  restoreStatus:
    includedResources:
    - workflows
    excludedResources: []
  includeClusterResources: null
  restorePVs: true
  scheduleName: <___>   !!!
