apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: schedule
  namespace: velero-ns
spec:
  # Every 5 min start, schedule
  schedule: '*/5 * * * *' 
  template:
    ttl: "720h"
    storageLocation: default
    includedNamespaces:
    - velero-ns
    includedResources:
    - 'pv'
    - 'pvc'
