apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: schedule
  namespace: velero-ns
  #annotations:
  #  velero.io/csi-volumesnapshot-class_disk.csi.cloud.com: "csi-vsphere-vsc"
spec:
  # Every 5 min start, schedule
  schedule: '*/5 * * * *' 
  template:
    ttl: "720h"
    storageLocation: default
    includedNamespaces:
    - velero-ns
    includedResources:
    - 'pv'
    - 'pvc'
