kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: test-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
